#ifndef OPTICSTOR_H
#define OPTICSTOR_H


#include <QMainWindow>
#include <QSqlQueryModel>
#include "client.h"
#include "produit.h"
#include "fournisseur.h"
//#include "commande.h"
#include "employe.h"
#include "metier.h"
#include "ravitaillementdialog.h"
#include "feedbackdialog.h"
#include <QChartView>
#include <QPieSeries>
#include <QTableWidget>          // ← AJOUTER
#include <QTableWidgetItem>      // ← AJOUTER
#include <QHeaderView>           // ← AJOUTER
#include <QTextDocument>
#include <QTextCursor>
#include <QPrinter>
#include <QFileDialog>
#include <QDesktopServices>
#include "camerawidget.h"
#include "cameraworker.h"
#include <QMessageBox>
#include <QSqlQuery>
#include "arduino.h"  // ← AJOUTER CETTE INCLUSION
#include <QSerialPort>  // ← IMPORTANT POUR LE PORT SÉRIE
#include <QSerialPortInfo>  // ← POUR DÉTECTER LES PORTS
#include <QThread>  // ← POUR LES PAUSES
using namespace std;

// The UI header generated by uic in this project defines a class named `Ui_opticstor`.
// Forward-declare that here so we match the generated header.
class Ui_opticstor;

class opticstor : public QMainWindow
{
    Q_OBJECT

public:
    opticstor(QWidget *parent = nullptr);
    ~opticstor();

    int getMaxAge();  // Déclaration de la nouvelle fonction
    int getAverageAge();  // Âge moyen
    int getClientCount(); // Nombre total de clients
    int getTestCount();   // Nombre total de tests


private slots:
    void update_label();  // ← AJOUTEZ CE SLOT À LA SECTION DES SLOTS
    void showAgeMaxWindow(int ageMax);  // AJOUTEZ CETTE LIGNE
    void showClientCountWindow(int nbClients);
    void showTestCountWindow(int nbTests); // Nouvelle fonction

    // Gestion des clients
    void on_ajouter_clicked();
    void on_supprimer_clicked();
    void on_modifier_clicked();
    void on_tableView_clicked(const QModelIndex &index);
    void on_rechercher_client_clicked();
    void on_statistique_age_clicked();
    void on_exporter_pdf_clicked();
    void on_combo_tri_currentIndexChanged(const QString &text);

    // Gestion des produits
    void on_ajouter_produit_clicked();
    void on_supprimer_produit_clicked();
    void on_modifier_produit_clicked();
    void on_rechercher_produit_clicked();
    void on_actualiser_produit_clicked();
    void on_exporter_pdf_produits_clicked();
    void on_combo_tri_produit_currentIndexChanged(int index);

 // SLOTS STOCK ET STATISTIQUES
    void on_btnRupture_clicked();
    void on_btnFaible_clicked();
    void on_btnNormal_clicked();
    void on_btnTous_clicked();
    void on_statistique_stock_clicked();
    void on_tendances_btn_clicked();

    // Gestion des fournisseurs
    void on_ajouter_fournisseur_clicked();
    void on_supprimer_fournisseur_clicked();
    void on_modifier_fournisseur_clicked();
    void on_rechercher_fournisseur_clicked();
    void on_actualiser_fournisseur_clicked();
    
    // Ravitaillement et Feedback fournisseur
    void on_ajoutravitalement_clicked();
    void on_feedback_clicked();
    void on_triparnom_clicked();
    void on_exportexel_clicked();
    void on_stat_fournisseur_clicked();
    void chargerRavitaillementTable();
    void showRavContextMenu(const QPoint &pos);
    void chargerTableFournisseurs();

    // Gestion des commandes
   /* void on_ajouter_commande_clicked();
    void on_supprimer_commande_clicked();
    void on_modifier_commande_clicked();
    void on_rechercher_commande_clicked();
    void on_actualiser_commande_clicked();
    void on_trier_date_commande_clicked();
    void on_trier_prix_commande_clicked();*/
    void ajoutcommande();
    void supprimcommande();
    void affichecommande();
    void updatecommande();
    void autrecmd();
    void loadtypesmarquesComboBox();
    void loadclientComboBox();
    void loademp();
    bool commandExists(int);
    void updmen();
    void rechcomd();
    void on_showChartButton_clicked();
    //void generateReceiptPDF(int);
    void createPDFReceipt(const QString &pdfPath,
                          const QString &customerName,
                          const QVector<QPair<QString,double>> &productList,
                          double totalPrice);


    void generatePDFForCommande(const QString &commandeId);
    void on_generatePDFButton_clicked();
    void on_commandSelected(int row, int column);


    // Gestion des employés
    void on_ajouter_employe_clicked();
    void on_supprimer_employe_clicked();
    void on_modifier_employe_clicked();
    void on_rechercher_employe_clicked();
    void on_actualiser_employe_clicked();

    // Gestion des tests d'ordonnance
    void on_ajouter_test_ordonnance_clicked();
    void on_supprimer_test_ordonnance_clicked();
    void on_afficher_tests_ordonnance_clicked();
    void on_rechercher_tests_client_clicked();

    // Gestion des feedbacks
    void on_ajouter_feedback_clicked();
    void on_annuler_feedback_clicked();
    void on_afficher_feedbacks_clicked();

    // statut
    void on_changer_statut_clicked();
    void on_rechercher_statut_clicked();
    void on_statistiques_statut_clicked();

    // Navigation
    void onGestCommande();
    void onGest();
    void onprod();
    void onemp();
    void onfourn();
    void onFeedbackPage();

    // Fonctions existantes
   /* void onSubmitClicked();
    void onCancelClicked();
    void onDeleteClicked();
    void onSubmitClickedd();
    void onCancelClickedd();
    void onDeleteClickedd();
    void onSearchClicked();
    void onEditClicked();
    void onEditClickedd();
    void onSortChanged(int index);*/









    // Gestion Arduino - NOUVEAUX SLOTS
     // Slot pour lire les données Arduino
    void on_boutonTestArduino_clicked();  // Bouton test dans l'interface
private:
    Ui_opticstor *ui;
    Client tmpClient;
    Produit tmpProduit;
    Fournisseur tmpFournisseur;
    //Commande tmpCommande;
    employe tmpEmploye;
    Metier tmpMetier;
    QChart *chart;
    QChartView *chartView;
    QTableWidget *ravitTable;
    QString type;
    QString marque;
    //int client;
    double prixtotal;
    int rech;
    cameraworker *worker;

    Arduino A;  // ← OBJET ARDUINO
    QByteArray data;

    QString genererHTMLClients(const QList<Client>& clients);

    //void remplirTableCommandes();
    void remplirTableClients();
    void remplirTableEmployes();
    void remplirTableTestsOrdonnance();
    void afficherStatistiquesAvecDurees();
    void setupTriComboBox();
    void setupTendances();
    void peuplerComboBox();

    // MÉTHODES PRODUITS ET STATISTIQUES
    QString genererHTMLProduits(const QList<Produit>& produits);
    void afficherStockSelonStatut(const QString& statut);
    QString determinerSexe(const QString& marque);
    void calculerEtAfficherTendances();
    void analyserVentesParModele();
    void analyserVentesParForme();// Nouvelle méthode pour afficher les stats avec durées

void envoyerMessageArduino(const QString& statut, int nombreProduits);

    void afficherStockSelonStatut(const QString& statut, int nombreProduits);
};

#endif // OPTICSTOR_H
