#include "metier.h"
#include <QSqlQuery>
#include <QSqlError>
#include <QSqlDatabase>
#include <QDebug>
#include <QDateTime>

Metier::Metier()
{
}

// ===== RAVITAILLEMENT =====

bool Metier::ajouterRavitaillementStandalone(int codeProduit, int idFournisseur, int quantite,
                                              const QString& message, int note, QString& erreur)
{
    QSqlDatabase db = QSqlDatabase::database();
    if (!db.isOpen()) {
        erreur = "Base de données non connectée";
        return false;
    }

    // Vérifier que la table RAVITAILLEMENTS existe, sinon la créer
    QSqlQuery checkTable(db);
    checkTable.exec("SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'RAVITAILLEMENTS'");
    if (checkTable.next() && checkTable.value(0).toInt() == 0) {
        // Créer la table
        QSqlQuery createTable(db);
        createTable.exec(
            "CREATE TABLE RAVITAILLEMENTS ("
            "ID_RAVITAILLEMENT NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "CODE_PRODUIT NUMBER, "
            "ID_FOURNISSEUR NUMBER, "
            "QUANTITE NUMBER DEFAULT 0, "
            "MESSAGE VARCHAR2(500), "
            "NOTE NUMBER DEFAULT 0, "
            "DATE_RAVITAILLEMENT DATE DEFAULT SYSDATE"
            ")"
        );
        if (createTable.lastError().isValid()) {
            qDebug() << "Erreur création table RAVITAILLEMENTS:" << createTable.lastError().text();
        }
    }

    QSqlQuery query(db);
    query.prepare("INSERT INTO RAVITAILLEMENTS (CODE_PRODUIT, ID_FOURNISSEUR, QUANTITE, MESSAGE, NOTE, DATE_RAVITAILLEMENT) "
                  "VALUES (:code, :fourn, :qte, :msg, :note, SYSDATE)");

    if (codeProduit > 0)
        query.bindValue(":code", codeProduit);
    else
        query.bindValue(":code", QVariant(QMetaType::fromType<int>()));

    if (idFournisseur > 0)
        query.bindValue(":fourn", idFournisseur);
    else
        query.bindValue(":fourn", QVariant(QMetaType::fromType<int>()));

    query.bindValue(":qte", quantite);
    query.bindValue(":msg", message);
    query.bindValue(":note", note);

    if (!query.exec()) {
        erreur = query.lastError().text();
        qDebug() << "Erreur ajout ravitaillement:" << erreur;
        return false;
    }

    // Si un produit est spécifié, mettre à jour son stock
    if (codeProduit > 0 && quantite > 0) {
           QSqlQuery updateStock(db);
           // Table is named PRODUIT and column names are CODE_PRODUIT / QUANTITE_STOCK
           updateStock.prepare("UPDATE PRODUIT SET QUANTITE_STOCK = NVL(QUANTITE_STOCK,0) + :qte WHERE CODE_PRODUIT = :code");
           updateStock.bindValue(":qte", quantite);
           updateStock.bindValue(":code", codeProduit);
           if (!updateStock.exec()) {
              qDebug() << "Erreur mise à jour stock:" << updateStock.lastError().text();
           }
    }

    qDebug() << "✅ Ravitaillement ajouté avec succès";
    return true;
}

QSqlQueryModel* Metier::afficherRavitaillement()
{
    QSqlQueryModel* model = new QSqlQueryModel();
    QSqlDatabase db = QSqlDatabase::database();

    if (!db.isOpen()) {
        qDebug() << "BD non connectée pour afficherRavitaillement";
        return model;
    }

    QSqlQuery query(db);
    query.prepare("SELECT ID_RAVITAILLEMENT, CODE_PRODUIT, ID_FOURNISSEUR, QUANTITE, MESSAGE, NOTE, DATE_RAVITAILLEMENT "
                  "FROM RAVITAILLEMENTS ORDER BY DATE_RAVITAILLEMENT DESC");

    if (!query.exec()) {
        qDebug() << "Erreur afficherRavitaillement:" << query.lastError().text();
        return model;
    }

    model->setQuery(std::move(query));
    model->setHeaderData(0, Qt::Horizontal, QObject::tr("ID"));
    model->setHeaderData(1, Qt::Horizontal, QObject::tr("Code Produit"));
    model->setHeaderData(2, Qt::Horizontal, QObject::tr("ID Fournisseur"));
    model->setHeaderData(3, Qt::Horizontal, QObject::tr("Quantité"));
    model->setHeaderData(4, Qt::Horizontal, QObject::tr("Message"));
    model->setHeaderData(5, Qt::Horizontal, QObject::tr("Note"));
    model->setHeaderData(6, Qt::Horizontal, QObject::tr("Date"));

    return model;
}

bool Metier::modifierRavitaillement(int id, int codeProduit, int idFournisseur, int quantite,
                                     const QString& message, int note, QString& erreur)
{
    QSqlDatabase db = QSqlDatabase::database();
    if (!db.isOpen()) {
        erreur = "Base de données non connectée";
        return false;
    }

    QSqlQuery query(db);
    query.prepare("UPDATE RAVITAILLEMENTS SET CODE_PRODUIT = :code, ID_FOURNISSEUR = :fourn, "
                  "QUANTITE = :qte, MESSAGE = :msg, NOTE = :note WHERE ID_RAVITAILLEMENT = :id");

    if (codeProduit > 0)
        query.bindValue(":code", codeProduit);
    else
        query.bindValue(":code", QVariant(QMetaType::fromType<int>()));

    if (idFournisseur > 0)
        query.bindValue(":fourn", idFournisseur);
    else
        query.bindValue(":fourn", QVariant(QMetaType::fromType<int>()));

    query.bindValue(":qte", quantite);
    query.bindValue(":msg", message);
    query.bindValue(":note", note);
    query.bindValue(":id", id);

    if (!query.exec()) {
        erreur = query.lastError().text();
        qDebug() << "Erreur modifierRavitaillement:" << erreur;
        return false;
    }

    if (query.numRowsAffected() == 0) {
        erreur = "Aucun ravitaillement trouvé avec cet ID";
        return false;
    }

    qDebug() << "✅ Ravitaillement modifié ID:" << id;
    return true;
}

bool Metier::supprimerRavitaillement(int id, QString& erreur)
{
    QSqlDatabase db = QSqlDatabase::database();
    if (!db.isOpen()) {
        erreur = "Base de données non connectée";
        return false;
    }

    QSqlQuery query(db);
    query.prepare("DELETE FROM RAVITAILLEMENTS WHERE ID_RAVITAILLEMENT = :id");
    query.bindValue(":id", id);

    if (!query.exec()) {
        erreur = query.lastError().text();
        qDebug() << "Erreur supprimerRavitaillement:" << erreur;
        return false;
    }

    if (query.numRowsAffected() == 0) {
        erreur = "Aucun ravitaillement trouvé avec cet ID";
        return false;
    }

    qDebug() << "✅ Ravitaillement supprimé ID:" << id;
    return true;
}

// ===== FEEDBACK =====

bool Metier::envoyerFeedback(int idFournisseur, const QString& message, int note, QString& erreur)
{
    QSqlDatabase db = QSqlDatabase::database();
    if (!db.isOpen()) {
        erreur = "Base de données non connectée";
        return false;
    }

    // Validate inputs to avoid DB constraint errors (ID_FOURNISSEUR NOT NULL, NOTE between 0 and 5)
    if (idFournisseur <= 0) {
        erreur = "ID fournisseur invalide (doit être > 0)";
        return false;
    }
    if (note < 0 || note > 5) {
        erreur = "La note doit être comprise entre 0 et 5";
        return false;
    }

    // Vérifier que la table FEEDBACKS existe (nom attendu dans votre schéma). Do not try to create complex storage/triggers here.
    QSqlQuery checkTable(db);
    checkTable.exec("SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'FEEDBACKS'");
    if (checkTable.next() && checkTable.value(0).toInt() == 0) {
        QSqlQuery createTable(db);
        // Create a simple version of the table if it does not exist. In a real DB you likely already have the sequence/trigger.
        createTable.exec(
            "CREATE TABLE FEEDBACKS ("
            "ID_FEEDBACK NUMBER PRIMARY KEY, "
            "ID_FOURNISSEUR NUMBER NOT NULL, "
            "MESSAGE VARCHAR2(1000), "
            "NOTE NUMBER(2,0), "
            "DATE_FEEDBACK DATE DEFAULT SYSDATE"
            ")"
        );
        if (createTable.lastError().isValid()) {
            qDebug() << "Erreur création table FEEDBACKS:" << createTable.lastError().text();
        }
    }

    QSqlQuery query(db);
    query.prepare("INSERT INTO FEEDBACKS (ID_FOURNISSEUR, MESSAGE, NOTE, DATE_FEEDBACK) "
                  "VALUES (:fourn, :msg, :note, SYSDATE)");
    query.bindValue(":fourn", idFournisseur);
    query.bindValue(":msg", message);
    query.bindValue(":note", note);

    if (!query.exec()) {
        erreur = query.lastError().text();
        qDebug() << "Erreur envoyerFeedback:" << erreur;
        return false;
    }

    qDebug() << "✅ Feedback envoyé pour fournisseur ID:" << idFournisseur;
    return true;
}

// ===== STATISTIQUES =====

QSqlQueryModel* Metier::statsFournisseur(int idFournisseur)
{
    QSqlQueryModel* model = new QSqlQueryModel();
    QSqlDatabase db = QSqlDatabase::database();

    if (!db.isOpen()) {
        qDebug() << "BD non connectée pour statsFournisseur";
        return model;
    }

    QSqlQuery query(db);
    
    if (idFournisseur <= 0) {
        // Tous les fournisseurs
        query.prepare(
            "SELECT ID_FOURNISSEUR, COUNT(*) AS NB_RAVITAILLEMENTS, "
            "SUM(QUANTITE) AS TOTAL_QUANTITE, ROUND(AVG(NOTE), 2) AS NOTE_MOYENNE "
            "FROM RAVITAILLEMENTS "
            "WHERE ID_FOURNISSEUR IS NOT NULL "
            "GROUP BY ID_FOURNISSEUR "
            "ORDER BY ID_FOURNISSEUR"
        );
    } else {
        // Un fournisseur spécifique
        query.prepare(
            "SELECT ID_FOURNISSEUR, COUNT(*) AS NB_RAVITAILLEMENTS, "
            "SUM(QUANTITE) AS TOTAL_QUANTITE, ROUND(AVG(NOTE), 2) AS NOTE_MOYENNE "
            "FROM RAVITAILLEMENTS "
            "WHERE ID_FOURNISSEUR = :id "
            "GROUP BY ID_FOURNISSEUR"
        );
        query.bindValue(":id", idFournisseur);
    }

    if (!query.exec()) {
        qDebug() << "Erreur statsFournisseur:" << query.lastError().text();
        return model;
    }

    model->setQuery(std::move(query));
    model->setHeaderData(0, Qt::Horizontal, QObject::tr("ID Fournisseur"));
    model->setHeaderData(1, Qt::Horizontal, QObject::tr("Nb Ravitaillements"));
    model->setHeaderData(2, Qt::Horizontal, QObject::tr("Total Quantité"));
    model->setHeaderData(3, Qt::Horizontal, QObject::tr("Note Moyenne"));

    return model;
}

QSqlQueryModel* Metier::statsParType()
{
    QSqlQueryModel* model = new QSqlQueryModel();
    QSqlDatabase db = QSqlDatabase::database();

    if (!db.isOpen()) {
        qDebug() << "BD non connectée pour statsParType";
        return model;
    }

    QSqlQuery query(db);
    query.prepare(
        "SELECT f.TYPE, COUNT(r.ID_RAVITAILLEMENT) AS NB_RAVITAILLEMENTS, "
        "SUM(r.QUANTITE) AS TOTAL_QUANTITE, ROUND(AVG(r.NOTE), 2) AS NOTE_MOYENNE "
        "FROM FOURNISSEURS f "
        "LEFT JOIN RAVITAILLEMENTS r ON f.ID_FOURNISSEUR = r.ID_FOURNISSEUR "
        "GROUP BY f.TYPE "
        "ORDER BY f.TYPE"
    );

    if (!query.exec()) {
        qDebug() << "Erreur statsParType:" << query.lastError().text();
        return model;
    }

    model->setQuery(std::move(query));
    model->setHeaderData(0, Qt::Horizontal, QObject::tr("Type"));
    model->setHeaderData(1, Qt::Horizontal, QObject::tr("Nb Ravitaillements"));
    model->setHeaderData(2, Qt::Horizontal, QObject::tr("Total Quantité"));
    model->setHeaderData(3, Qt::Horizontal, QObject::tr("Note Moyenne"));

    return model;
}
